# Generated by Django 5.2.14 on 2026-05-11 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(choices=[('GENERAL_INQUIRY', 'General Inquiry'), ('ORDER_ISSUE', 'Order Issue'), ('PRODUCT_FEEDBACK', 'Product Feedback'), ('TECHNICAL_SUPPORT', 'Technical Support')], db_index=True, default='GENERAL_INQUIRY', max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, help_text='অ্যাডমিন মেসেজটি পড়েছেন কিনা।')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='idx_inquiry_email'), models.Index(fields=['subject'], name='idx_inquiry_subject'), models.Index(fields=['is_read'], name='idx_inquiry_is_read'), models.Index(fields=['created_at'], name='idx_inquiry_created')],
            },
        ),
    ]
