# Generated by Django 5.2.14 on 2026-05-10 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆ — Very Poor'), (2, '★★☆☆☆ — Poor'), (3, '★★★☆☆ — Average'), (4, '★★★★☆ — Good'), (5, '★★★★★ — Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
